name: Deploy GitHub Repository

on:
  push:
    branches: [ main, 'sprint/**', 'release/**' ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository (if necessary)
        run: |
          if [ ! -d /home/runner/repository ]; then
            # Clone repository only if it doesn't exist
            git clone git@github.com:sky-uk/Emulator_Manifest.git /home/runner/repository
          fi

     
